server:
  port: 8081
  servlet:
    context-path: /
  tomcat:
    threads:
      max: 200
      min-spare: 50
    connection-timeout: 5000ms
    accept-count: 100
    max-connections: 8192
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.st.entity
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-field: 0
      logic-not-delete-value: 1
    banner: false
  executor-type: simple
  configuration:
    local-cache-scope: session
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: null
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/st?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1
      minimum-idle: 50
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 5000
        max-idle: 5000
        min-idle: 2000
        max-wait: 5000ms
    connect-timeout: 5000ms
    password: 123456
  transaction:
    rollback-on-commit-failure: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 50
        max-concurrency: 100
        prefetch: 1
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 3
          max-interval: 10000ms
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
management:
  endpoints:
    web:
      exposure:
        include: 'health,metrics'
myself:
  limit:
    user:
      time: 3
    entrance:
      time: 100
  expired: 10
  jvmstart: /home/start.sh
