dubbo:
  application:
    name: socket
  provider:
    connections: 100
  consumer:
    check: false
    filter: metrics
  protocol:
    name: dubbo
    port: -1
  registry:
    id: zk-registry
    address: zookeeper://101.42.164.61:2181
  config-center:
    address: zookeeper://101.42.164.61:2181
  metadata-report:
    address: zookeeper://101.42.164.61:2181

